config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :like_notes
    end
  end
  root   'home#top'
  get    '/about' => 'home#about'
  resources :notes, only: [:show, :create, :edit, :update, :destroy] do
    member do
      get :liking_users
    end
  end
  post '/like/:note_id' => 'likes#like', as: 'like'
  delete '/unlike/:note_id' => 'likes#unlike', as: 'unlike'

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :note
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  validates :title, presence: true
  validates :content, presence: true, length: {maximum: 140}
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable
  has_many :likes
  has_many :notes
  has_many :like_notes, through: :likes, source: :note
#  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  def set_image(file)
    if !file.nil?
      file_name = file.original_filename
      File.open("public/user_images/#{file_name}", 'wb'){|f| f.write(file.read)}
      self.image = file_name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include ApplicationHelper

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
  end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    if user_signed_in?
      @note = Note.new
      @notes = Note.all.order(created_at: :desc)
    else
      @message = "welcome to gatebook!"
    end
  end
  def about
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def like
    @note = Note.find(params[:note_id])
    like = current_user.likes.build(note_id: @note.id)
    like.save
  end
  def unlike
    @note = Note.find(params[:note_id])
    like = current_user.likes.find_by(note_id: @note.id)
    like.destroy
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def show
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to @note, notice: "submission was updated."
    else
      render :edit
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path
  end

  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      redirect_to @note, notice: "submission was saved."
    else
      @notes = Note.all.order(created_at: :desc)
      render 'home/top'
    end
  end

  private
  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :content)
  end

  def correct_user
    note = Note.find(params[:id])
    if !currentuser?(note.user)
      redirect_to root_path, alert: 'Not allowed!'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :like_notes]

  # GET /users/:id/likes
  def like_notes
    @notes = @user.like_notes
    @title = "liked! list"
    render :show
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @notes = @user.notes
    @title = "Submission List"
  end

  # GET /users/new
#  def new
#    @user = User.new
#  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
#  def create
#    @user = User.new(user_params)
#    # save image
#    @user.set_image(params[:user][:image])
#
#    respond_to do |format|
#      if @user.save
#        format.html { redirect_to @user, notice: 'User was successfully created.' }
#        format.json { render :show, status: :created, location: @user }
#      else
#        format.html { render :new }
#        format.json { render json: @user.errors, status: :unprocessable_entity }
#      end
#    end
#  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update

    # save image
    @user.set_image(params[:user][:image])

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
#  def destroy
#    @user.destroy
#    respond_to do |format|
#      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
#      format.json { head :no_content }
#    end
#  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end

    def correct_user
      user = User.find(params[:id])
      unless current_user.id == user.id
        redirect_to root_path, alert: 'Edit is not allowed!'
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def currentuser?(user)
    current_user.id == user.id
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def image_for(user)
    if user.image
      image_tag "/user_images/#{user.image}", class: "profile_img"
    else
      image_tag "wanko.png", class: "profile_img"
    end
  end
end

app/views/home/about.html.erb
<div class='container'>
  <h1>what is gatebook?</h1>
  <p>gatebook is a sns site made by rails.</p>
</div>

app/views/home/top.html.erb
<% if user_signed_in? %>
  <aside class="sidebar">
    <%= render 'notes/form' %>
  </aside>
  <ul class="notes">
    <h2>Submission List</h2>
    <%= render @notes %>
  </ul>
<% else %>
  <div class="top-wrapper">
    <%= image_tag "gatebook_cover.png" %>
    <div class="register-wrapper">
      <h1><%= @message %></h1>
      <%= link_to "New Register", new_user_registration_path, class: "btn btn-large register-btn" %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gatebook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar">
<div id="logo"><%= link_to "Gatebook", root_path %></div>
  <% if user_signed_in? %>
    <ul class="header-right">
      <li><%= link_to "User List", users_path %></li>
      <li><%= link_to current_user.email, current_user %></li>
      <li><%= link_to "logout",  destroy_user_session_path, method: :delete %></li>

    </ul>
  <% else %>
    <ul class="header-right">
      <li><%= link_to "Outline", about_path %></li>
      <li><%= link_to "new user", new_user_registration_path %></li>
      <li><%= link_to "login", new_user_session_path %></li>
    </ul>
  <% end %>
</header>
<p class="alert alert-success"><%= notice %></p>
<p class="alert alert-danger"><%= alert %></p>

<div class="container"><%= yield %></div> 

<div class="container">
  <footer class="footer">
    <div class="small">
     &copy; 2017 Progate, Inc.
    </div>
  </footer>
</div>

</body>
</html>

app/views/likes/_like_links.html.erb
<% if current_user.likes.find_by(note_id: @note.id) %>
  <%= link_to "Unlike", unlike_path(@note.id), method: "delete", remote: true %>
<% else %>
  <%= link_to "Like", like_path(@note.id), method: "post", remote: true %>
<% end %>

app/views/likes/like.js.erb
$('#like-link').html('<%=escape_javascript(render("likes/like_links", note: @note)) %>');
$('#like-count').html('<%= @note.likes.count %>');

app/views/likes/unlike.js.erb
$('#like-link').html('<%=escape_javascript(render("likes/like_links", note: @note)) %>');
$('#like-count').html('<%= @note.likes.count %>');

app/views/notes/_form.html.erb
<% if @note.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2><%= @note.errors.count %> errors</h2>
    <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@note) do |f| %>
  Title
  <%= f.text_field :title, class: 'form-control title-field' %>
  Content
  <%= f.text_area :content, class: 'form-control content-field' %>
  <%= f.submit "submission", class: 'btn primary-btn' %>
<% end %>

app/views/notes/_note.html.erb
  <span>
    <%= note.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
  </span>
  <li>
    <span class="user-name">
      <%= note.user.name %>
    </span>
    <span class="content">
      <%= link_to note.title, note_path(note.id) %>
    </span>
  </li>
  <div>
    <small>
      <%= note.likes.count  %> liked
    </small>
  </div>

app/views/notes/edit.html.erb
<h1>Edit Submission</h1>
<%= render 'form' %>

app/views/notes/index.html.erb
<h1>Submission List</h1>
<ul class="notes">
 <%= render @notes %>
</ul>

app/views/notes/liking_users.html.erb
<ul class='show-note'>
  <%= render @note %>
</ul>

<h2 class="heading">liking user list</h2>
<ul class='user-list'>
  <%= render @users %>
</ul>

app/views/notes/new.html.erb
<h1>new submission</h1>
<%= render 'form' %>

app/views/notes/show.html.erb
<p id="notice" class="alert alert-success">
  <%= notice %>
</p>
<h2>Title</h2>
<p><%= @note.title %></p>
<h2>Content</h2>
<p><%= @note.content %></p>
<% if currentuser?(@note.user) %>
<%= link_to 'Edit', edit_note_path(@note.id), class: 'btn edit-btn' %>
<%= link_to "Delete", note_path(@note.id), method: "delete", class: "btn destroy-btn", "data-comfirm" => "yes?" %>
<% end %>
<div id="like-link">
  <%=render "likes/like_links", note: @note %>
</div>
<div>
  <small>
    <%= link_to @note.likes.count, liking_users_note_path(@note.id), id: 'like-count' %> liked
  </small>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: 'form-control image-field' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= image_for(user) %>
  <%= link_to user.name, user %> |
  <%= user.email %>
</li>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_for(user) %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <% if current_user.id == user.id %>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <% end %>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_for(@user) %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<% if currentuser?(@user) %>
<%= link_to 'Edit', edit_user_path(@user) %> |
<% end %>
<%= link_to 'Back', users_path %>

<ul class="notes">
  <h2><%= @title %></h2>
  <%= render @notes %>
</ul>
<%= link_to @user.likes.count, like_notes_user_path(@user.id) %> liked.